spring:
  main:
    allow-bean-definition-overriding: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hackathon2?currentSchema=public
    username: postgres
    password: postgres

server:
  port: 3005
  servlet:
    context-path: /back
