DROP TABLE IF EXISTS userr;
DROP TABLE IF EXISTS answer;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS test;
DROP TABLE IF EXISTS activity;
DROP TABLE IF EXISTS specification;



CREATE TABLE specification
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)
);


CREATE TABLE userr
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         varchar(30)  NOT NULL UNIQUE,
    password         varchar(100) NOT NULL,
    first_name       varchar(30)  NOT NULL,
    last_name        varchar(30)  NOT NULL,
    father_name      varchar(30)  NOT NULL,
    email            varchar(100) NOT NULL UNIQUE,
    is_admin         boolean,
    specification_id bigint REFERENCES specification (id)
);

CREATE TABLE activity
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             varchar(100),
    specification_id bigint REFERENCES specification (id)
);

--TODO ДОБАВИТЬ ПОРЯДОК ТЕСТОВ!
CREATE TABLE test
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id bigint REFERENCES activity (id)
);

CREATE TABLE question
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    varchar(100),
    test_id bigint REFERENCES test (id)
);

CREATE TABLE answer
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(100),
    is_correct  boolean,
    question_id bigint REFERENCES question (id)
);



INSERT INTO specification(name)
VALUES ('Хирург'),
       ('Терапевт'),
       ('Педиатр'),
       ('Травматолог'),
       ('Онколог');

INSERT INTO userr(username, password, first_name, last_name, father_name, email, is_admin, specification_id)
VALUES
-- Пароль у всех "12345"
('ivan45', '12345', 'Иван', 'Петров', 'Петрович', 'ivan45@gmail.com', false, 1),
('egor002', '12345', 'Егор', 'Сидоров', 'Алексеевич', 'egor34@gmail.com', false, 4),
('dima99', '12345', 'Дмитрий', 'Алексеев', 'Викторович', 'dima22@gmail.com', true, null);

INSERT INTO activity(name)
VALUES ('Нейрохирургия'),
       ('Нейрохирургия №2'),
       ('Первая помощь пострадавшим'),
       ('Лечение температуры'),
       ('Лечение температуры №2');

INSERT INTO test(activity_id)
VALUES (1),
       (1),
       (2),
       (4),
       (5);


INSERT INTO question(name, test_id)
VALUES ('Первый вопрос первого теста нейрохирургии', 1),
       ('Второй вопрос первого теста нейрохирургии', 1),
       ('Первый вопрос второго теста нейрохирургии', 2),
       ('Первый вопрос нейрохирургии №2', 3),
       ('Второй вопрос нейрохирургии №2', 3);

INSERT INTO answer(name, is_correct, question_id)
VALUES ('Первый ответ', false, 1),
       ('Второй ответ', false, 1),
       ('Третий ответ (Правильный)', true, 1),
       ('Четвертый ответ', false, 1),

       ('Первый ответ', false, 2),
       ('Второй ответ (Правильный)', true, 2),
       ('Третий ответ ', false, 2),
       ('Четвертый ответ', false, 2),

       ('Первый ответ', false, 3),
       ('Второй ответ', false, 3),
       ('Третий ответ (Правильный)', true, 3),
       ('Четвертый ответ', false, 3),

       ('Первый ответ', false, 4),
       ('Второй ответ', false, 4),
       ('Третий ответ (Правильный)', true, 4),
       ('Четвертый ответ (Правильный)', true, 4);




